import type { Metadata } from 'next';
import { Inter, Open_Sans, Roboto } from 'next/font/google';

import Header from '@/Components/Header';

import './globals.css';

import Footer from '@/Components/Footer';

const inter = Inter({ subsets: ['latin'] });

const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
});

const openSans = Open_Sans({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: '2DIGITS Assignment',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={` ${inter.className} ${roboto.variable} ${openSans.variable}`}>
        <Header />

        {children}

        <Footer />
      </body>
    </html>
  );
}
